#!/bin/sh

osascript <<EOF
tell application "Tunnelblick"
    connect "client"
    get state of first configuration where name = "client"
    repeat until result = "CONNECTED"
        delay 1
        get state of first configuration where name = "client"
    end repeat
end tell
EOF
